# Generated by Django 3.2.8 on 2021-10-09 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStampBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('timestampbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TheEyeApp.timestampbase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TheEyeApp.userextension')),
            ],
            bases=('TheEyeApp.timestampbase',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('timestampbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TheEyeApp.timestampbase')),
                ('name', models.CharField(max_length=150)),
                ('data', models.JSONField()),
                ('session_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TheEyeApp.session')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TheEyeApp.eventtype')),
            ],
            bases=('TheEyeApp.timestampbase',),
        ),
    ]
