# Generated by Django 3.2.8 on 2021-10-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheEyeApp', '0002_application_app_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_secret',
            field=models.CharField(default='KoQPuHYkBNqcEhbyaDwxlpfAnSWIzZ', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='session_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_set', to='TheEyeApp.session'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_set', to='TheEyeApp.eventtype'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheEyeApp.userextension'),
        ),
    ]
