# Generated by Django 3.2.8 on 2021-10-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('TheEyeApp', '0003_auto_20211011_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='session_event',
        ),
        migrations.AddField(
            model_name='event',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_set', to='TheEyeApp.application'),
        ),
        migrations.AddField(
            model_name='event',
            name='session_django',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_set', to='sessions.session'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TheEyeApp.userextension'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_secret',
            field=models.CharField(default='JdHZoyQnMpsaNhjBXzxYOivqSflgWt', max_length=30),
        ),
    ]
