# Generated by Django 3.2.8 on 2021-10-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheEyeApp', '0005_auto_20211013_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='need_required_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='required_fields',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_secret',
            field=models.CharField(default='OjqAdRZLXxbgEeSCQBwcVsWvGNYkMo', max_length=30),
        ),
    ]
